name: un-og-training-dev
channels:
- conda-forge
dependencies:
- python>=3.10, <3.12
- numpy
- scipy
- pandas
- ipython
- matplotlib
- bokeh
- sphinx
- sphinx-argparse
- sphinxcontrib-bibtex>=2.0.0
- sphinx-math-dollar
- pydata-sphinx-theme
- jupyter-book>=0.11.3
- jupyter
- black
- setuptools
- pytest
- pytest-cov
- coverage
- pip
- pip:
  - ogcore
  - ogusa
  - linecheck
  - yaml-changelog
  - sphinx-exercise
  - git+https://github.com/EAPD-DRB/OG-ZAF.git
  - sphinx-proof
  - sphinx_subfigure
